### ISSUE TITLE
Insufficient memory for > 30,000 cells

### ISSUE THREAD

**Issue by JEFworks** [hms-dbmi/pagoda2#17] opened 2017-09-13 13:25 UTC
Variance normalization, KNN, cluster detection, and tSNE embedding seem to spuriously fail if I have more than 30,000 cells due to insufficient memory issues. Such large datasets with >30,000 cells will likely be more common in the near future. Other fields like Cytof have already developed solutions for these problems such as by doing density based subsampling. I would recommend we implement something similar.

**Comment by pkharchenko** [comment] 2017-09-13 13:28
Jean, please specify the failure details (i.e. the lines where the failure occurs) so that this can be debugged.

**Comment by JEFworks** [comment] 2017-09-13 14:03
Error is primarily occurring (and can be reliably reproduced) when getting the tSNE embedding
```
> rcomb$getEmbedding(type = 'PCA', embeddingType = 'tSNE', verbose=TRUE, perplexity=100)                                                                   
 calculating distance ... pearson ...                                                                                                                       
  *** caught segfault ***                                                                                                                                   
 address 0x7f36ac07ea00, cause 'memory not mapped'                                                                                                          
                                                                                                                                                            
 Traceback:                                                                                                                                                 
  1: cor(t(x), method = "pearson")                                                                                                                          
  2: as.matrix(1 - cor(t(x), method = "pearson"))                                                                                                           
  3: rcomb$getEmbedding(type = "PCA", embeddingType = "tSNE", verbose = TRUE,     perplexity = 100)                                                         
                                                                                                                                                            
 Possible actions:                                                                                                                                          
 1: abort (with core dump, if enabled)                                                                                                                      
 2: normal R exit                                                                                                                                           
 3: exit R without saving workspace                                                                                                                         
 4: exit R saving workspace                                                                                                                                 
 Selection:    
```

**Comment by pkharchenko** [comment] 2017-09-13 14:11
The error is a bit odd. It should report something like “cannot allocate memory” if we’re hitting the memory limit (we shouldn’t hitting it in C under 64bit OS). Might be worth doing a quick Rcpp check to see if a matrix of such size indeed fails to allocate.

But I agree that the downsampling could be useful at this stage. My suggestion would be to estimate local density from kNN graph and downsample accordingly. But would need to play with this to see how different P_sampling(density) functions affect tSNE results.

**Comment by barkasn** [comment] 2017-09-13 19:23
I saw similar errors occurring while consolidating the KNN methods. "memory not mapped" is not a memory allocation error but rather an error in passing objects back into R from Rcpp. In my experient this occurs when the underlying object has gone out of scope in C or you are trying to return a NULL

**Comment by JEFworks** [comment] 2017-09-14 00:19
Confirming that we do indeed get a different error message if the matrix is too big:
```
> library(Matrix)                                                                                                                                                               
> x <- Matrix(data=0,nrow=1e5,ncol=1e5,sparse=TRUE)                                                                                                                             
> d <- as.dist(1-cor(as.matrix(t(x)), method = 'pearson'))                                                                                                                   
 Error in asMethod(object) :                                                                                                                                                  
   Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105 
```

And that our memory not mapped error is being caused by something in C++ related to Rtsne.multicore:
```
> library(Matrix)                                                                                                                                                               
> x <- Matrix(data=0,nrow=100,ncol=30000,sparse=TRUE)                                                                                                                           
> d <- as.dist(1-cor(as.matrix(t(x)), method = 'pearson'))                                                                                                                      
> library(Rtsne.multicore)                                                                                                                                                      
> emb <- Rtsne.multicore(d, is_distance=TRUE, perplexity=30, num_threads=10)$Y                                                                                                  
*** caught segfault *** 
address 0x8, cause 'memory not mapped'
Traceback:                                                                                                                                                                   
 .Call("_Rtsne_multicore_Rtsne_cpp", PACKAGE = "Rtsne.multicore",     X, no_dims_in, perplexity_in, theta_in, num_threads, max_iter,     distance_precomputed)                
  1: .Call("_Rtsne_multicore_Rtsne_cpp", PACKAGE = "Rtsne.multicore",     X, no_dims_in, perplexity_in, theta_in, num_threads, max_iter,     distance_precomputed)            
  2: Rtsne_cpp(X, dims, perplexity, theta, num_threads, max_iter,     is_distance) 2:  1: .Call("_Rtsne_multicore_Rtsne_cpp", PACKAGE = "Rtsne.multicore",     X, no_dims_in,\
  perplexity_in, theta_in, num_threads, max_iter,     distance_precomputed)                                                                                                   
  2: Rtsne_cpp(X, dims, perplexity, theta, num_threads, max_iter,     is_distance)                                                                                            
  3: eval(expr, pf) 
```

The error persists even when we use num_threads=1 or when we use the non-multicore Rtsne package and functions, so it's not a threading issue.

**Comment by pkharchenko** [comment] 2017-09-14 00:48
The p2 devel branch has switched to Rtsne openmp branch. Can you test that please.
Thanks,
-peter.

**Comment by JEFworks** [comment] 2017-09-14 17:54
Issue does appear to be resolved with Rtsne openmp. The following executes without error:

```
## try openmp version                                                                                                                                                                             
library(devtools)                                                                                                                                                                                 
devtools::install_github('jkrijthe/Rtsne', ref='openmp')                                                                                                                                          
library(Rtsne)                                                                                                                                                                                    
                                                                                                                                                                                                  
# simulate large sparse matrix                                                                                                                                                                    
library(Matrix)                                                                                                                                                                                   
N <- 3e3                                                                                                                                                                                          
M <- 3e4                                                                                                                                                                                          
x <- Matrix(data=0,nrow=N,ncol=M,sparse=TRUE)                                                                                                                                                     
d <- as.dist(1-cor(as.matrix(t(x)), method = 'pearson'))                                                                                                                                          
d[is.na(d)] <- 0                                                                                                                                                                                  
library(Rtsne)                                                                                                                                                                                    
emb <- Rtsne(d, is_distance=TRUE, perplexity=30)
```

**Comment by JEFworks** [comment] 2017-09-15 01:45
Now getting different error with even bigger matrix (almost 70,000 cells). 

```
> d <- dist(x) 
> dim(x)                                                                                                                             
 [1] 69131    16                                                                                                                      
> emb <- Rtsne(d, is_distance=TRUE, perplexity=100)                                                                                  
 Error in complete.cases(object) :                                                                                                    
   long vectors not supported yet: complete_cases.c:111
```

Problem is resolved with smaller matrix
```
d <- dist(x[1:100,])                                                                                                                  
emb <- Rtsne(d, is_distance=TRUE, perplexity=10)
```

Seems to be related to this: https://stackoverflow.com/questions/24335692/large-matrices-in-r-long-vectors-not-supported-yet

**Comment by barkasn** [comment] 2018-02-07 13:35
Couple of points on this that might be helpful in the future: (1) The problem is related to how many non-sparse entries there are in the matrix. In some occasions they exceed the R vector limit. This is only indirectly related to the number fo cells. (2) For embedding the current version calculates correlation distance before running tSNE, this should give better embeddings but it can fail if there are too many cells, try distance='L2' on getEmbedding() if that happens.

**Comment by pkharchenko** [comment] 2019-01-19 00:21
testing on R 3.4.1 and still hitting this problem. At ~70k cells, tSNE on L2 distances works fine, but correlation distance calculation fails ... specifically, cor(x) fails with a segfault (memory unmapped) ... seems like an old bug in R. Such large distance matrices are impractical to calculate, but it shouldn't crash. I've added a size check, switching to 'L2' if there are over 40k cells.  largeVis is more practical for such sizes.
9cb282c03a7ceb3eadc3cc0fdddf5e39e6565821

**Closed by pkharchenko** 2019-01-19 00:21 UTC
Labels: enhancement
