### ISSUE TITLE
Chrome Webinterface Bug

### ISSUE THREAD

**Issue by Simontuk** [hms-dbmi/pagoda2#19] opened 2017-09-28 13:40 UTC
This applies to the current devel-branch.
When using Chrome _Version 61.0.3163.100_ on Mac OS with a static file some parts of the heatmap fail to show. It was reproducible for showing multiple genes, but it also sometimes happens for the aspect-Heatmap when first loading the interface.  

It seems to have to do with the Javascript Error:

> RemoteFileReader.js:33 GET http://pklab.med.harvard.edu/nikolas/pagoda2/staticDemo/10xPBMC.bin net::ERR_CACHE_OPERATION_NOT_SUPPORTED

![image](https://user-images.githubusercontent.com/11211791/30969291-ed81cb08-a42f-11e7-8f90-1ae7dc031c3d.png)

**Comment by barkasn** [comment] 2017-09-28 14:30
Could you please add specific gene selection steps that will reproduce the bugs?

**Comment by Simontuk** [comment] 2017-09-28 14:41
Steps to reproduce bug shown in post:
1. In Gene selection click on any gene. 
2. Shift-click on another to select a selection of genes (n>3). 
Genes won't be displayed properly as shown in screenshot above.

**Comment by barkasn** [comment] 2017-10-26 12:37
This is directly related to this known Chrome bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=77085

It can probably be overcome by ensuring that the server returns a valid range descriptors as discussed in the thread

**Comment by barkasn** [comment] 2018-08-14 02:54
Fixed with commit #c00db3b

The issue is chrome specific and results in unexpected failures of ajax requests. Fixed by adding random string at the end of file requests performed in Chrome only. This may have a speed penalty in slow connections from Chrome specifically. Similar errors have been reported by other web apps that read large files over the web e.g. IGV.js

**Closed by barkasn** 2018-08-14 02:54 UTC
Labels: bug
